# Generated by Django 5.2.8 on 2025-11-17 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Compte Utilisateur Associé')),
                ('agent_code', models.CharField(max_length=20, unique=True, verbose_name='Code Agent')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name="Date d'Embauche")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['agent_code'],
            },
        ),
    ]
