# Generated by Django 5.2.8 on 2025-11-17 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TollSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_number', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'Abonné")),
                ('registration_plate', models.CharField(max_length=20, unique=True, verbose_name="Plaque d'Immatriculation")),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Solde Actuel')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Compte Utilisateur')),
            ],
            options={
                'verbose_name': 'Abonné au Péage',
                'verbose_name_plural': 'Abonnés au Péage',
                'ordering': ['subscriber_number'],
            },
        ),
    ]
