# Generated by Django 5.2.8 on 2025-11-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipements_api', '0001_initial'),
        ('suiveurs_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveillance_date', models.DateTimeField(auto_now_add=True, verbose_name='Date et Heure de Surveillance')),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('ANOMALY', 'Anomalie'), ('RESOLVED', 'Résolu')], default='NORMAL', max_length=20, verbose_name='Statut')),
                ('report', models.TextField(blank=True, null=True, verbose_name="Rapport d'Observation")),
                ('equipement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipements_api.equipement', verbose_name='Équipement Surveillé')),
                ('suiveur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suiveurs_api.suiveur', verbose_name='Suiveur Responsable')),
            ],
            options={
                'verbose_name': 'Surveillance',
                'verbose_name_plural': 'Surveillances',
                'ordering': ['-surveillance_date'],
            },
        ),
    ]
