# Generated by Django 5.2.8 on 2025-11-17 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caissier',
            fields=[
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agents_api.agent', verbose_name='Agent Associé')),
                ('matricule_caissier', models.CharField(max_length=20, unique=True, verbose_name='Matricule du Caissier')),
                ('is_trained', models.BooleanField(default=True, verbose_name='Est Formé')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Caissier',
                'verbose_name_plural': 'Caissiers',
                'ordering': ['matricule_caissier'],
            },
        ),
    ]
