# Generated by Django 5.2.8 on 2025-11-17 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suiveur',
            fields=[
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agents_api.agent', verbose_name='Agent Associé (Suiveur)')),
                ('matricule_suiveur', models.CharField(max_length=20, unique=True, verbose_name='Matricule du Suiveur')),
                ('is_field_agent', models.BooleanField(default=True, verbose_name='Est Agent de Terrain')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Suiveur',
                'verbose_name_plural': 'Suiveurs',
                'ordering': ['matricule_suiveur'],
            },
        ),
    ]
