# Generated by Django 5.2.8 on 2025-11-17 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabines_api', '0001_initial'),
        ('responsables_api', '0001_initial'),
        ('sites_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervision_date', models.DateTimeField(auto_now_add=True, verbose_name='Date et Heure de Supervision')),
                ('grade', models.CharField(choices=[('A', 'Excellent'), ('B', 'Bon'), ('C', 'Moyen'), ('D', 'Insatisfaisant')], default='A', max_length=20, verbose_name="Note d'Audit")),
                ('summary', models.TextField(verbose_name="Résumé de l'Audit")),
                ('is_closed', models.BooleanField(default=False, verbose_name='Audit Clos')),
                ('cabine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabines_api.cabine', verbose_name='Cabine Spécifique Auditée')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsables_api.responsable', verbose_name='Responsable Auditeur')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites_api.site', verbose_name='Site Audité')),
            ],
            options={
                'verbose_name': 'Supervision',
                'verbose_name_plural': 'Supervisions',
                'ordering': ['-supervision_date'],
            },
        ),
    ]
