# Generated by Django 5.2.8 on 2025-11-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom du Site')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code du Site (Identifiant court)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est Actif')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['name'],
            },
        ),
    ]
