# Generated by Django 5.2.8 on 2025-11-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabines_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de Série')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'Équipement")),
                ('status', models.CharField(choices=[('ONLINE', 'En Ligne'), ('OFFLINE', 'Hors Ligne'), ('MAINTENANCE', 'Maintenance')], default='OFFLINE', max_length=20, verbose_name='Statut')),
                ('last_check', models.DateTimeField(auto_now=True, verbose_name='Dernière Vérification')),
                ('is_active', models.BooleanField(default=True)),
                ('cabine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabines_api.cabine', verbose_name="Cabine d'Installation")),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['serial_number'],
            },
        ),
    ]
