# Generated by Django 5.2.8 on 2025-11-17 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repartition_date', models.DateField(verbose_name='Date de Répartition')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Réparti')),
                ('category', models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte'), ('OTHER', 'Autre')], default='CASH', max_length=50, verbose_name='Catégorie de Répartition')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Détails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites_api.site', verbose_name='Site de Répartition')),
            ],
            options={
                'verbose_name': 'Répartition',
                'verbose_name_plural': 'Répartitions',
                'ordering': ['-repartition_date'],
            },
        ),
    ]
