# Generated by Django 5.2.8 on 2025-11-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du Type')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code Court')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
            ],
            options={
                'verbose_name': 'Type de Véhicule',
                'verbose_name_plural': 'Types de Véhicules',
                'ordering': ['code'],
            },
        ),
    ]
