# Generated by Django 5.2.8 on 2025-11-17 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('C1', 'Classe 1 (Véhicules légers)'), ('C2', 'Classe 2 (Intermédiaires)'), ('C3', 'Classe 3 (Poids lourds 2 essieux)'), ('C4', 'Classe 4 (Poids lourds 3+ essieux)')], max_length=50, verbose_name='Classe de Véhicule')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du Tarif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est Actif')),
                ('start_date', models.DateField(verbose_name="Date d'Activation")),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites_api.site', verbose_name='Site/Tronçon Appliqué')),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarifs',
                'ordering': ['site__name', 'vehicle_type'],
                'unique_together': {('site', 'vehicle_type', 'is_active')},
            },
        ),
    ]
