# Generated by Django 5.2.8 on 2025-11-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True, verbose_name='Libellé du Type')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code Catégorie')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de Véhicule',
                'verbose_name_plural': 'Types de Véhicules',
            },
        ),
    ]
