# Generated by Django 5.2.8 on 2025-11-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents_api', '0001_initial'),
        ('sites_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_date', models.DateTimeField(auto_now_add=True, verbose_name='Date et Heure du Contrôle')),
                ('result', models.CharField(choices=[('OK', 'Conforme'), ('KO', 'Non Conforme'), ('PARTIAL', 'Partiellement Conforme')], default='OK', max_length=20, verbose_name='Résultat')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Commentaires')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents_api.agent', verbose_name='Agent Contrôleur')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites_api.site', verbose_name='Site Contrôlé')),
            ],
            options={
                'verbose_name': 'Contrôle',
                'verbose_name_plural': 'Contrôles',
                'ordering': ['-control_date'],
            },
        ),
    ]
