# Generated by Django 5.2.8 on 2025-11-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code AME')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'Entité AME")),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Personne Contact')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AME',
                'verbose_name_plural': 'AMES',
                'ordering': ['name'],
            },
        ),
    ]
