# Generated by Django 5.2.8 on 2025-11-17 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabine_number', models.CharField(max_length=10, unique=True, verbose_name='Numéro de Cabine')),
                ('direction', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie')], max_length=10, verbose_name='Direction')),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites_api.site', verbose_name='Site Associé')),
            ],
            options={
                'verbose_name': 'Cabine',
                'verbose_name_plural': 'Cabines',
                'ordering': ['site__name', 'cabine_number'],
                'unique_together': {('site', 'cabine_number')},
            },
        ),
    ]
