# Generated by Django 5.2.8 on 2025-11-17 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents_api', '0001_initial'),
        ('sites_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agents_api.agent', verbose_name='Agent Associé (Responsable)')),
                ('matricule_responsable', models.CharField(max_length=20, unique=True, verbose_name='Matricule du Responsable')),
                ('is_active', models.BooleanField(default=True)),
                ('managed_sites', models.ManyToManyField(blank=True, to='sites_api.site', verbose_name='Sites Gérés')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'ordering': ['matricule_responsable'],
            },
        ),
    ]
