# Generated by Django 5.2.8 on 2025-11-17 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receveur',
            fields=[
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agents_api.agent', verbose_name='Agent Associé (Receveur)')),
                ('matricule_receveur', models.CharField(max_length=20, unique=True, verbose_name='Matricule du Receveur')),
                ('is_supervisor', models.BooleanField(default=False, verbose_name='Est Superviseur')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Receveur',
                'verbose_name_plural': 'Receveurs',
                'ordering': ['matricule_receveur'],
            },
        ),
    ]
