# Generated by Django 5.2.8 on 2025-11-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabines_api', '0001_initial'),
        ('caissiers_api', '0001_initial'),
        ('sites_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(max_length=100, unique=True, verbose_name='Référence Transaction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant Encaissé')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('CARD', 'Carte'), ('SUBSCRIBER', 'Abonné')], default='CASH', max_length=20, verbose_name='Méthode de Paiement')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('cabine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabines_api.cabine', verbose_name='Cabine')),
                ('caissier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caissiers_api.caissier', verbose_name='Caissier')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites_api.site', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Recette',
                'verbose_name_plural': 'Recettes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
