# Generated by Django 5.2.8 on 2025-11-17 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caissiers_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manquant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_manquant', models.DateField(verbose_name='Date du Manquant')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du Manquant (en devise locale)')),
                ('justification', models.TextField(blank=True, null=True, verbose_name='Justification ou Commentaire')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Est Résolu')),
                ('caissier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caissiers_api.caissier', verbose_name='Caissier Concerné')),
            ],
            options={
                'verbose_name': 'Manquant',
                'verbose_name_plural': 'Manquants',
                'ordering': ['-date_manquant', 'montant'],
            },
        ),
    ]
