# Generated by Django 5.2.8 on 2025-11-17 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caissiers_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('REMISE', 'Remise de Fonds'), ('VERSEMENT', 'Versement'), ('SORTIE', 'Sortie de Caisse')], max_length=50, verbose_name='Type de Transaction')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise (ISO 4217)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('notes', models.TextField(blank=True, null=True)),
                ('caissier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caissiers_api.caissier', verbose_name='Caissier Opérateur')),
            ],
            options={
                'verbose_name': "Mouvement d'Argent",
                'verbose_name_plural': "Mouvements d'Argent",
                'ordering': ['-timestamp'],
            },
        ),
    ]
