# Generated by Django 5.2.8 on 2025-11-17 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du Type')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code Court')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
            ],
            options={
                'verbose_name': 'Type de Véhicule',
                'verbose_name_plural': 'Types de Véhicules',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'Immatriculation")),
                ('owner_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du Propriétaire')),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='get_vehicles_api.vehicletype')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['registration_number'],
            },
        ),
    ]
